# Generated by Django 4.2.30 on 2026-05-24 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("joined_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataUploadBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP Procurement ERP"),
                            ("UTILITY", "Utility Portal Export"),
                            ("CONCUR", "Concur Corporate Travel"),
                        ],
                        max_length=15,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("original_file_name", models.CharField(max_length=255)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pipeline.companyclient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarbonDataRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Analyst Review"),
                            ("APPROVED", "Approved & Locked for Audit"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "ghg_scope",
                    models.IntegerField(
                        choices=[
                            (1, "Scope 1 (Direct Emissions - e.g., Fuel)"),
                            (2, "Scope 2 (Indirect Emissions - e.g., Electricity)"),
                            (3, "Scope 3 (Value Chain - e.g., Business Travel)"),
                        ]
                    ),
                ),
                ("is_finalized_and_locked", models.BooleanField(default=False)),
                ("has_data_anomaly", models.BooleanField(default=False)),
                ("anomaly_explanation", models.TextField(blank=True, null=True)),
                ("source_system_line_id", models.CharField(max_length=100)),
                ("unmodified_data_snapshot", models.TextField()),
                ("emission_activity_type", models.CharField(max_length=100)),
                (
                    "raw_quantity_entered",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                ("raw_unit_entered", models.CharField(max_length=20)),
                (
                    "normalized_quantity",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                ("normalized_unit", models.CharField(max_length=20)),
                (
                    "calculated_carbon_footprint_kg",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                ("accounting_date", models.DateField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pipeline.companyclient",
                    ),
                ),
                (
                    "upload_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pipeline.datauploadbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalystChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action_performed",
                    models.CharField(default="MANUAL_EDIT", max_length=50),
                ),
                ("audit_trail_details", models.TextField()),
                (
                    "data_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="pipeline.carbondatarow",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
